before_install:
  - sudo add-apt-repository -y ppa:nschloe/boost-nightly
  - sudo apt-get update -qq
addons: 
  apt: 
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages: 
      - g++-6
      - clang-3.8
      - boost1.67
compiler: 
  - gcc
  - clang
install: 
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
language: cpp
script: 
  - make
  - make test
sudo: false
