addons: 
  apt: 
    packages: 
      - g++-6
      - clang-3.8
      - libboost-all-dev
compiler: 
  - gcc
  - clang
install: 
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
language: cpp
script: 
  - make
  - ./test
sudo: false
